version: x.x.{build}
image: Visual Studio 2019
configuration: Release
install:
- cmd: >-
    appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1

    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 3.0.100-preview8-013656 -InstallDir "%ProgramFiles%\dotnet" -Architecture x64

    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 3.0.100-preview8-013656 -InstallDir "%ProgramFiles(x86)%\dotnet" -Architecture x86
before_build:
- cmd: appveyor-retry nuget restore
build_script:
- cmd: build.cmd
test: off
before_package:
- cmd: msbuild /t:Pack /p:Configuration=Release
artifacts:
- path: Iced\bin\Release\*.*nupkg
  name: Iced NuGet Packages
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: en/ChGrnyp08i9CgI/8WXLKhl0OHCpPsuBSRv9wt286kvKlI9P4732egbzq+ycfx
